name: Build CLDiagnostic

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Test
        run: |
          echo "GitHub Actions funciona correctamente"
          sw_vers
          xcodebuild -version
